export default {
  GET_ACTIVE_AOS: 'GET_ACTIVE_AlGO_ORDERS',
  SET_ACTIVE_AOS: 'SET_ACTIVE_AlGO_ORDERS',
  HANDLE_ACTIVE_AOS: 'HANDLE_ACTIVE_AlGO_ORDERS',
  SHOW_ACTIVE_AOS_MODAL: 'SHOW_ACTIVE_AlGO_ORDERS_MODAL',
}
