module.exports = {
  POSITIONS_SNAPSHOT: 'BFX_DATA_PS',
  POSITION_UPDATE: 'BFX_DATA_PU',
  POSITION_CLOSE: 'BFX_DATA_PC',

  ORDERS_SNAPSHOT: 'BFX_DATA_OS',
  ORDER_NEW: 'BFX_DATA_ON',
  ORDER_UPDATE: 'BFX_DATA_OU',
  ORDER_CLOSE: 'BFX_DATA_OC',

  TICKER: 'BFX_DATA_TICKER',
  NOTIFICATION: 'BFX_DATA_NOTIFICATION',

  RECV_CHANNEL_DATA: 'BFX_RECV_CHANNEL_DATA',
  RECV_ORDER_DATA: 'BFX_RECV_ORDER_DATA',

  FLUSH_BOOK_DATA: 'BFX_FLUSH_BOOK_DATA',
  FLUSH_TRADES_DATA: 'FLUSH_TRADES_DATA',
  FLUSH_ORDER_DATA: 'FLUSH_ORDER_DATA',
}
