module.exports = {
    GA_AO_CANCEL: 'GA_AO_CANCEL',
    GA_PAGEVIEW: 'GA_PAGEVIEW',
    GA_CANCEL_AO: 'GA_CANCEL_AO',
    GA_CANCEL_ATOMIC_ORDER: 'GA_CANCEL_ATOMIC_ORDER',
    GA_CREATE_STRATEGY: 'GA_CREATE_STRATEGY',
    GA_SUBMIT_ATOMIC_ORDER: 'GA_SUBMIT_ATOMIC_ORDER',
    GA_SUBMIT_AO: 'GA_SUBMIT_AO',
    GA_UPDATE_SETTINGS: 'GA_UPDATE_SETTINGS'
}