export default {
  CHANGE_SUBSCRIPTIONS: 'MARKET_CHANGE_SUBSCRIPTIONS',
  GET_CCY_FULL_NAMES: 'MARKET_GET_CCY_FULL_NAMES',
  SET_CCY_FULL_NAMES: 'MARKET_SET_CCY_FULL_NAMES',
  GET_PERPS_NAMES: 'MARKET_GET_PERPS_NAMES',
  SET_PERPS_NAMES: 'MARKET_SET_PERPS_NAMES',
}
