export default {
  GET_SETTINGS: 'GET_SETTINGS',
  SET_SETTINGS: 'SET_SETTINGS',
  UNAUTH_SETTING: 'UNAUTH_SETTING',
  SET_SETTINGS_MULTI: 'SET_SETTINGS_MULTI',
  DELETE_SETTINGS: 'DELETE_SETTINGS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  SET_MAP_SETTING: 'SET_MAP_SETTING',
  TOGGLE_BOOLEAN_SETTING: 'TOGGLE_BOOLEAN_SETTING',
  SET_INITIAL_SETTINGS: 'SET_INITIAL_SETTINGS',
}

export const ALL_KEYS = '*'

export const DEFAULT_USER_SETTINGS_MAP = {}
