module.exports = {
  SAVE_REMOTE_VERSION: 'SAVE_REMOTE_VERSION',
  SAVE_COMPONENT_STATE: 'UI_SAVE_COMPONENT_STATE',
  UPDATE_COMPONENT_STATE: 'UI_UPDATE_COMPONENT_STATE',
  SAVE_LAYOUT: 'UI_SAVE_LAYOUT',
  STORE_UNSAVED_LAYOUT: 'UI_STORE_UNSAVED_LAYOUT',
  CREATE_LAYOUT: 'UI_CREATE_LAYOUT',
  DELETE_LAYOUT: 'UI_DELETE_LAYOUT',

  SET_LAYOUT_ID: 'UI_SET_LAYOUT_ID',
  ADD_COMPONENT: 'UI_ADD_COMPONENT',
  REMOVE_COMPONENT: 'UI_REMOVE_COMPONENT',
  CHANGE_LAYOUT: 'UI_CHANGE_LAYOUT',
  SELECT_LAYOUT: 'UI_SELECT_LAYOUT',

  SET_ACTIVE_MARKET: 'SET_SAVE_MARKET',
  SET_ACTIVE_EXCHANGE: 'UI_SET_ACTIVE_EXCHANGE',
  SET_FILTRED_VALUE: 'SET_FILTRED_VALUE',

  UPDATE_SETTINGS: 'UPDATE_SETTINGS',

  CLOSE_NOTIFICATIONS: 'CLOSE_NOTIFICATIONS',
  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
  REMOVE_NOTIFICATIONS: 'REMOVE_NOTIFICATIONS',
  CLEAR_NOTIFICATIONS: 'CLEAR_NOTIFICATIONS',
  OPEN_NOTIFICATIONS: 'OPEN_NOTIFICATIONS',
  SWITCH_NOTIFICATIONS: 'SWITCH_NOTIFICATIONS',
  FIRST_LOGIN: 'FIRST_LOGIN',

  TRADING_PAGE: 'TRADING_TERMINAL',
  MARKET_PAGE: 'MARKET_DATA',
  STRATEGY_PAGE: 'STRATEGY_EDITOR',
  SETTINGS_PAGE: 'SETTINGS',

  FINISH_GUIDE: 'FINISH_GUIDE',

  DATA_NOTIFICATION: 'UI_DATA_NOTIFICATION',
  STRATEGY_SELECT: 'STRATEGY_SELECT',
  UPDATE_STRATEGY_ID: 'UPDATE_STRATEGY_ID',
  UPDATE_STRATEGY_CONTENT: 'UPDATE_STRATEGY_CONTENT',
  CLEAR_STRATEGIES: 'CLEAR_STRATEGIES',

  SET_TRADING_MODE: 'SET_TRADING_MODE',
  SET_MARKET_FROM_STORE: 'SET_MARKET_FROM_STORE',
  SET_IS_ORDER_EXECUTING: 'SET_IS_ORDER_EXECUTING',
  CHANGE_TRADING_MODAL_STATE: 'CHANGE_TRADING_MODAL_STATE',
  CHANGE_BAD_INTERNET_STATE: 'CHANGE_BAD_INTERNET_STATE',
  CHANGE_REFILL_BALANCE_MODAL_STATE: 'CHANGE_REFILL_BALANCE_MODAL_STATE',
  CHANGE_TICKERS_VOLUME_UNIT: 'UI_CHANGE_TICKERS_VOLUME_UNIT',
}
