module.exports = {
  SAVE_REMOTE_VERSION: 'SAVE_REMOTE_VERSION',
  SAVE_COMPONENT_STATE: 'UI_SAVE_COMPONENT_STATE',
  SAVE_LAYOUT: 'UI_SAVE_LAYOUT',
  CREATE_LAYOUT: 'UI_CREATE_LAYOUT',
  DELETE_LAYOUT: 'UI_DELETE_LAYOUT',

  SET_ROUTE: 'UI_SET_ROUTE',

  SET_ACTIVE_MARKET: 'SET_SAVE_MARKET',
  SET_ACTIVE_EXCHANGE: 'UI_SET_ACTIVE_EXCHANGE',
  SET_FILTRED_VALUE: 'SET_FILTRED_VALUE',
  SET_BACKTESTING_PAGE: 'SET_BACKTESTING_PAGE',

  UPDATE_SETTINGS: 'UPDATE_SETTINGS',

  CLOSE_NOTIFICATIONS: 'CLOSE_NOTIFICATIONS',
  OPEN_NOTIFICATIONS: 'OPEN_NOTIFICATIONS',
  FIRST_LOGIN: 'FIRST_LOGIN',

  TRADING_PAGE: 'TRADING_TERMINAL',
  MARKET_PAGE: 'MARKET_DATA',
  STRATEGY_PAGE: 'STRATEGY_EDITOR',
  SETTINGS_PAGE: 'SETTINGS',

  FINISH_GUIDE: 'FINISH_GUIDE',

  DATA_NOTIFICATION: 'UI_DATA_NOTIFICATION',
  STRATEGY_SELECT: 'STRATEGY_SELECT',
  UPDATE_STRATEGY_ID: 'UPDATE_STRATEGY_ID',
  UPDATE_STRATEGY_CONTENT: 'UPDATE_STRATEGY_CONTENT',
}
