module.exports = {
  SAVE_COMPONENT_STATE: 'UI_SAVE_COMPONENT_STATE',
  SAVE_LAYOUT: 'UI_SAVE_LAYOUT',
  CREATE_LAYOUT: 'UI_CREATE_LAYOUT',
  DELETE_LAYOUT: 'UI_DELETE_LAYOUT',

  SET_ROUTE: 'UI_SET_ROUTE',

  SET_ACTIVE_MARKET: 'SET_SAVE_MARKET',
  SET_ACTIVE_EXCHANGE: 'UI_SET_ACTIVE_EXCHANGE',
}
