export default {
  ERROR: 'WS_BFX_ERROR',
  SEND: 'WS_BFX_SEND',
  BUFF_SEND: 'WS_BFX_BUFF_SEND',
  CONNECT: 'WS_BFX_CONNECT',
  DISCONNECT: 'WS_BFX_DISCONNECT',
  CONNECTED: 'WS_BFX_CONNECTED',
  DISCONNECTED: 'WS_BFX_DISCONNECTED',
  AUTHENTICATED: 'WS_BFX_AUTHENTICATED',
  FLUSH_QUEUE: 'WS_BFX_FLUSH_QUEUE'
}
