export default {
  ERROR: 'ERROR',
  SEND: 'SEND',
  BUFF_SEND: 'BUFF_SEND',
  CONNECT: 'CONNECT',
  DISCONNECT: 'DISCONNECT',
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  AUTHENTICATED: 'AUTHENTICATED'
}
