export default {
  CALC: 'WS_HF_CALC',
  BFX_SUBSCRIBE: 'WS_HF_BFX_SUBSCRIBE',
  BFX_UNSUBSCRIBE: 'WS_HF_BFX_UNSUBSCRIBE',
  ERROR: 'WS_HF_ERROR',
  SEND: 'WS_HF_SEND',
  BUFF_SEND: 'WS_HF_BUFF_SEND',
  CONNECT: 'WS_HF_CONNECT',
  DISCONNECT: 'WS_HF_DISCONNECT',
  CONNECTED: 'WS_HF_CONNECTED',
  RECONNECTED: 'WS_HF_RECONNECTED',
  DISCONNECTED: 'WS_HF_DISCONNECTED',
  FLUSH_QUEUE: 'WS_HF_FLUSH_QUEUE'
}
